export const products = 
[
  {
      "Id":  "1",
      "Category":  "THERMOSTAT",
      "Name":  "\"T9 SMART THERMOSTAT\"",
      "Price":  "179.99",
      "Image":  "RCHT9610WFSW2003W-c7-6.jpg",
      "DecImage1":  "HoneywellHome_Logo_Red_NP.png",
      "DecRollImages":  "P1-1.jpg|P1-2.jpg|P1-3.jpg",
      "DecContent1":  "T9 Smart Thermostat with Sensor",
      "DecContent2":  "RCHT9610WFSW2003/U",
      "DecContent3":  "A temperature thats just right. Every night.",
      "DecContent4":  "Sense the temperatures in the places that matter most with the T9 Smart Thermostat. Focus on the rooms you choose by adding Smart Room Sensors and setting a schedule or let the sensors respond to your lifestyle.",
      "DecSelectAModel":  "T9 Smart Thermostat with Sensor|T9 Smart Thermostat",
      "DecSpec1Image":  "P1-4.jpg",
      "DecSpec1Content1":  "PRODUCT OVERVIEW",
      "DecSpec1Content2":  "The T9 Smart Thermostat works with Smart Room Sensors to help you adjust the temperature from anywhere and stay cozy in the rooms that matter.                                            Place sensors where you want to see each room\u0027s temperature and humidity. Use the multi-room display on the thermostat\u0027s touchscreen  or in the Honeywell Home app  to focus on rooms based on occupancy or a specific schedule you choose. When focusing on multiple rooms, the T9 works toward creating an average temperature, balancing the needs across the whole home.                                                                                                                                                                                                                                                                                Whether its a song belted in the shower or a whispered secret, your air goes beyond simply carrying oxygen to circulating memories. Heavy or light, hot or cold, always unique to your home, the air you feel is more than its temperature setting. Our Air products and services work with you and for you, supporting and creating more comfortable surroundings.",
      "DecSpec2Image":  "P1-5.png",
      "DecSpec2Content1":  "Take It All With You",
      "DecSpec2Content2":  "Manage your Honeywell Home devices in the easy-to-use app, making it simple to control home comfort, monitor usage and more  from anywhere.                                                        Worry less  get alerts if temperatures rise above or fall below your threshold as well as reminders to change your air filter. Plus, you dont always know your schedule week-to-week. With location-based home and away modes, your smart thermostat can respond to your lifestyle, automatically adjusting your temperature and passing the savings onto you.",
      "Page_URL":  "https://www.resideo.com/us/en/products/air/thermostats/wifi-thermostats/t9-smart-thermostat-rcht9510wfw2001-u/"
  },
  {
      "Id":  "2",
      "Category":  "THERMOSTAT",
      "Name":  "\"T1 Non-Programmable Thermostat\"",
      "Price":  "179.1",
      "Image":  "TH1110D2009-c7-6.jpg",
      "DecImage1":  "HoneywellHome_Logo_Red_NP.png",
      "DecRollImages":  "P2-1.jpg|P2-2.jpg|P2-3.jpg",
      "DecContent1":  "T1 Non-Programmable Thermostat",
      "DecContent2":  "TH1110D2009/U",
      "DecContent3":  "A temperature thats just right. Every night.",
      "DecContent4":  "T1 Pro non-Programmable thermostat for 24 Vac systems, single stage heat only or cool only systems.",
      "DecSelectAModel":  "T1 Pro Non-Programmable Thermostat - 24 Vac|T1 Non-Programmable Thermostat",
      "DecSpec1Image":  "P2-4.jpg",
      "DecSpec1Content1":  "PRODUCT OVERVIEW",
      "DecSpec1Content2":  "The T1 Pro Non-Programmable Thermostat from Resideo is one of the best choices in terms of temperature control on the market.                                                                                                               Features include:                                                                                                                                                                                                                                                                                                                                        Simple installation                                                                                                                                                                                                                                                                                                                                    Push-button control                                                                                                                                                                                                                                                                                                                          Sleek aesthetic                                                                                                                                                                                                                                                                                                                                    Easy to read display                                                                                                                                                                                                                                                                                                                                               24 Vac systems; gas, oil, electric warm air; hot water coil; gas, oil, electric hydronic; or steam / gravity systems                                                                                                                                        Up to 1 heat or 1 cool conventional systems                                                                                                                                                                                                                                                                                                           5 to 90% RH, non-condensing operating humidity range (% RH)                                                                                                                                                                                                                                            Battery or hardwired power method                                                                                                                                                                                                                                                                                                    Includes thermostat, UWP mounting system, installation (J-box) adapter",
      "DecSpec2Image":  "",
      "DecSpec2Content1":  "Features                                                                                                                                                                                                                                                                                                                                                   T1 Non-Programmable Thermostat",
      "DecSpec2Content2":  "Simple to Install, Push-Button Control                                                                                                                                                                                                                                                                                                        Easy to install and easy to read with a display size of 2.37 in., the T1 Pro Non-Programmable Thermostat makes temperature in your home simple. With push-button control and a sleek aesthetic, it will fit right into any decor.",
      "Page_URL":  "https://www.resideo.com/us/en/products/air/thermostats/non-programmable-thermostats/t1-non-programmable-thermostat-th1110d2009-u/"
  },
  {
      "Id":  "3",
      "Category":  "THERMOSTAT",
      "Name":  "\"THE ROUND SMART THERMOSTAT\"",
      "Price":  "249",
      "Image":  "TH8732WF-c8-6.jpg",
      "DecImage1":  "HoneywellHome_Logo_Red_NP.png",
      "DecRollImages":  "P3-1.jpg|P3-2.jpg|P3-3.jpg",
      "DecContent1":  "The Round Smart Thermostat",
      "DecContent2":  "RCH9310WF5003/U",
      "DecContent3":  "Imagine a thermostat that adapts to you.",
      "DecContent4":  "The Round Smart Thermostat measures humidity and temperature and adjusts to your comfort level automatically as you come and go. Blend comfort and efficiency to fit your lifestyle with this ENERGY STAR certified and intelligent smart home thermostat.",
      "DecSelectAModel":  "The Round Smart Thermostat",
      "DecSpec1Image":  "P3-4.jpg",
      "DecSpec1Content1":  "PRODUCT OVERVIEW",
      "DecSpec1Content2":  "Intelligent comfort control is at your fingertips with The Round Smart Thermostat.                                                                                                                                                                                                   Now the temperature you set is always the temperature you feel thanks to dual temperature and humidity monitoring. View and adjust the humidity levels in your home remotely when you connect your WiFi thermostat to the Honeywell Home app.                                                                                                                                                                                                                 Smart and adaptive, The Round Smart Thermostat knows when you\u0027re home or away and automatically adjusts the temperature to maintain comfort and manage energy costs. It can even send notifications when it\u0027s time to change the air filter or perform other maintenance.                                                                                                                                                             Whether its a song belted in the shower or a whispered secret, your air goes beyond simply carrying oxygen to circulating memories. Heavy or light, hot or cold, always unique to your home, the air you feel is more than its temperature setting. Our Air products and services work with you and for you, supporting and creating more comfortable surroundings.",
      "DecSpec2Image":  "P3-5.png",
      "DecSpec2Content1":  "Take It All With You",
      "DecSpec2Content2":  "The Round Smart Thermostat is supported by our Honeywell Home App, which lets you control your Honeywell Home devices from anywhere, in one connected platform.            The app\u0027s one-touch dashboard brings heating and cooling control, water leak detection and security all together with activity alerts, smart home integration, improved geofencing and improved usability.",
      "Page_URL":  "https://www.resideo.com/us/en/products/air/thermostats/wifi-thermostats/the-round-smart-thermostat-rch9310wf5003-u/"
  },
  {
      "Id":  "4",
      "Category":  "THERMOSTAT",
      "Name":  "Prestige IAQ Thermostat with RedLINK",
      "Price":  "249.01",
      "Image":  "YTHX9421R5101WW-c2-6.jpg",
      "DecImage1":  "HoneywellHome_Logo_Red_NP.png",
      "DecRollImages":  "P4-1.jpg",
      "DecContent1":  "Prestige IAQ Kit with RedLINK, EIM and Sensors",
      "DecContent2":  "YTHX9421R5101WW/U",
      "DecContent3":  "Imagine a thermostat that adapts to you.",
      "DecContent4":  "One Thermostat. Advanced Whole-Home Comfort.                                                                                                                                                                                                                                                                                                         You\u0027re in control with the Honeywell Home Prestige IAQ 2.0 Thermostat. This device lets you control your entire home\u0027s comfort via temperature, humidification, air-conditioning and ventilation. RedLINK Technology lets you adjust these settings remotely.                                                   ",
      "DecSelectAModel":  "Prestige IAQ Kit with RedLINK, EIM and 4 Sensors|Prestige IAQ Kit with RedLINK, EIM, and 2 Sensors",
      "DecSpec1Image":  "P4-4.png",
      "DecSpec1Content1":  "PRODUCT OVERVIEW",
      "DecSpec1Content2":  " The Prestige IAQ Thermostat with RedLINK features an effortless, 7-day programmable color touchscreen that provides control of temperature, humidification, dehumidification and ventilation. Its high-definition, full-color display is easy to read. The thermostat interviews you and uses your answers to program itself.                                     No need to work through complicated settings and instructions. Optional add-ons include the Portable Comfort Control that allows you to adjust room temperatures from anywhere in the home.",
      "DecSpec2Image":  "P4-5.png",
      "DecSpec2Content1":  "Take It All With You",
      "DecSpec2Content2":  "Gain control over their connected devices from anywhere at any time through the Total Connect Comfort App. You can monitor and adjust heating and cooling usage, stay on top of indoor humidity levels, and automatically receive email alerts related to safety, comfort and energy. The app works with a wide range of popular connected devices.",
      "Page_URL":  "https://www.resideo.com/us/en/products/air/thermostats/programmable-thermostats/prestige-iaq-kit-with-redlink-eim-and-2-sensors-ythx9421r5127ww-u/"
  },
  {
      "Id":  "5",
      "Category":  "THERMOSTAT",
      "Name":  "Wi-Fi Smart Thermostat",
      "Price":  "249.02",
      "Image":  "RTH9580WF1005-c2-6.jpg",
      "DecImage1":  "HoneywellHome_Logo_Red_NP.png",
      "DecRollImages":  "P5-1.jpg|P5-2.jpg",
      "DecContent1":  "Wi-Fi Smart Thermostat",
      "DecContent2":  "RTH9580WF1005/U1",
      "DecContent3":  "Imagine a thermostat that adapts to you.",
      "DecContent4":  "Customizable, connected and ENERGY STAR certified, Wi-Fi Smart Thermostats offer a simple setup and come in multiple colors to compliment your dcor.                                           This product has be discontinued.  Please see product RTH9585 for the current product.",
      "DecSelectAModel":  "Wi-Fi Smart Thermostat|",
      "DecSpec1Image":  "P5-4.jpg",
      "DecSpec1Content1":  "PRODUCT OVERVIEW",
      "DecSpec1Content2":  "With a sleek aesthetic and large customizable touchscreen, your Wi-Fi Smart Thermostat will blend right in with your home dcor. Choose a color to accent the surroundings as easily as you adjust the temperature. This smart thermostat also connects to your existing Wi-Fi to give you control from your smart device via the Total Connect Comfort app. Check in from virtually anywhere and adjust or reschedule on the fly. With 7-day programming you can set a heating/cooling schedule that fits your lifestyle. Come home to your ideal temperature knowing you saved energy while you were away.\n            ",
      "DecSpec2Image":  "P5-5.png",
      "DecSpec2Content1":  "Take It All With You",
      "DecSpec2Content2":  "Gain control over their connected devices from anywhere at any time through the Total Connect Comfort App. You can monitor and adjust heating and cooling usage, stay on top of indoor humidity levels, and automatically receive email alerts related to safety, comfort and energy. The app works with a wide range of popular connected devices.",
      "Page_URL":  "https://www.resideo.com/us/en/products/air/thermostats/programmable-thermostats/wi-fi-smart-thermostat-rth9580wf1005-u1/"
  },
  {
      "Id":  "6",
      "Category":  "THERMOSTAT",
      "Name":  "Standard Non-Programmable Thermostat",
      "Price":  "249.03",
      "Image":  "CT50K1002-c1-6.jpg",
      "DecImage1":  "HoneywellHome_Logo_Red_NP.png",
      "DecRollImages":  "P6-1.jpg|P6-2.jpg",
      "DecContent1":  "Standard Heat Only Manual Thermostat",
      "DecContent2":  "CT50K1002/E1",
      "DecContent3":  "Worry-Free Heating and Cooling",
      "DecContent4":  "This Standard Non-Programmable Thermostat is easy to install and even easier to use with its lever control and clearly marked modes. With worry-free operation, DIY installation and a one-year warranty, this thermostat provides peace of mind and simplified control.",
      "DecSelectAModel":  "Standard Heat Only Manual Thermostat",
      "DecSpec1Image":  "",
      "DecSpec1Content1":  "",
      "DecSpec1Content2":  "",
      "DecSpec2Image":  "",
      "DecSpec2Content1":  "",
      "DecSpec2Content2":  "",
      "Page_URL":  "https://www.resideo.com/us/en/products/air/thermostats/non-programmable-thermostats/standard-heat-only-manual-thermostat-ct50k1002-e1/"
  },
  {
      "Id":  "7",
      "Category":  "THERMOSTAT",
      "Name":  "T5+ SMART THERMOSTAT",
      "Price":  "149",
      "Image":  "RCHT8612WF-c4-6.jpg",
      "DecImage1":  "HoneywellHome_Logo_Red_NP.png",
      "DecRollImages":  "P7-1.jpg|P7-2.jpg|P7-3.jpg",
      "DecContent1":  "T5+ Smart Thermostat with C-Wire Adapter",
      "DecContent2":  "RCHT8612WF2005/U",
      "DecContent3":  "Keeping life in tune",
      "DecContent4":  "The T5+ Smart Thermostat gives you comfort knowing your home temperature is always to your liking. This app-controlled thermostat is easy to install and conveniently fits your lifestyle. Program it based on your schedule, or let it automatically adapt as plans change.",
      "DecSelectAModel":  "T5+ Smart Thermostat|T5+ Smart Thermostat with C-Wire Adapter",
      "DecSpec1Image":  "P7-4.jpg",
      "DecSpec1Content1":  "PRODUCT OVERVIEW",
      "DecSpec1Content2":  "T5+ Smart Thermostat helps to make your home the most comfortable temperature when you arrive by using geofencing technology to keep track of your smart phone\u0027s location. By not heating or cooling your home until you\u0027re close to home, the smart home thermostat can save you money on energy costs while you\u0027re away.                                       Connect your WiFi thermostat to the Honeywell Home App, a platform designed to simplify your home comfort with a single app. Control from anywhere by smartphone or tablet, and receive push notifications to remind you to change your filter and warn you of extreme indoor temperatures.                                                                                                                             Whether its a song belted in the shower or a whispered secret, your air goes beyond simply carrying oxygen to circulating memories. Heavy or light, hot or cold, always unique to your home, the air you feel is more than its temperature setting. Our Air products and services work with you and for you, supporting and creating more comfortable surroundings.",
      "DecSpec2Image":  "P7-5.png",
      "DecSpec2Content1":  "Take It All With You",
      "DecSpec2Content2":  "The T5+ Smart Thermostat is supported by our Honeywell Home App, which lets you control your Honeywell Home devices from anywhere, in one connected platform.                   The app\u0027s one-touch dashboard brings heating and cooling control, water leak detection and security all together with activity alerts, smart home integration, improved geofencing and improved usability.",
      "Page_URL":  "https://www.resideo.com/us/en/products/air/thermostats/wifi-thermostats/t5-smart-thermostat-with-c-wire-adapter-rcht8612wf2005-u/"
  },
  {
      "Id":  "8",
      "Category":  "THERMOSTAT",
      "Name":  "VisionPRO 8000 WiFi Programmable Thermostat",
      "Price":  "149.01",
      "Image":  "YTH8321WF-c2-6.jpg",
      "DecImage1":  "HoneywellHome_Logo_Red_NP.png",
      "DecRollImages":  "P8-1.jpg|P8-2.jpg",
      "DecContent1":  "Fresh Air Ventilation Kit with 6 in. Damper",
      "DecContent2":  "YTH8321WF1036/U",
      "DecContent3":  "Clarity, Connectivity, and Control",
      "DecContent4":  "With a large touchscreen display, the VisionPRO 8000 WiFi Programmable Thermostat makes it easy to control your home comfort. Program a schedule for every day of the week or control the temperature remotely anytime from the Total Connect Comfort app.",
      "DecSelectAModel":  "Fresh Air Ventilation Kit with 8 in. Damper|VisionPRO 8000 WiFi Programmable Thermostat|Fresh Air Ventilation Kit with 6 in. Damper",
      "DecSpec1Image":  "P8-4.jpg",
      "DecSpec1Content1":  "PRODUCT OVERVIEW",
      "DecSpec1Content2":  "Connect to comfort and control with the VisionPRO 8000 WiFi Programmable Thermostat. Set a schedule for each day of the week and adjust it using the Total Connect Comfort app. When connected to the app, you can control the system remotely and receive alerts for maintenance or extreme temperatures. Select models feature a thermostat with humidifier control (TH8321) for fine-tuned comfort.                                                                                                                                                                                                                                   The large touchscreen display is easy to read and shows the  status of all equipment controlled by the thermostat. It can also present your dealer information if you need to reach out for service or questions.",
      "DecSpec2Image":  "P8-5.png",
      "DecSpec2Content1":  "Take It All With You",
      "DecSpec2Content2":  "Gain control over their connected devices from anywhere at any time through the Total Connect Comfort App. You can monitor and adjust heating and cooling usage, stay on top of indoor humidity levels, and automatically receive email alerts related to safety, comfort and energy. The app works with a wide range of popular connected devices.",
      "Page_URL":  "https://www.resideo.com/us/en/products/air/thermostats/wifi-thermostats/fresh-air-ventilation-kit-with-6-in-damper-yth8321wf1036-u/"
  },
  {
      "Id":  "9",
      "Category":  "THERMOSTAT",
      "Name":  "FocusPRO 6000 Programmable Wireless Thermostat",
      "Price":  "149.02",
      "Image":  "YTH6320R1001-c2-6.jpg",
      "DecImage1":  "HoneywellHome_Logo_Red_NP.png",
      "DecRollImages":  "P9-1.jpg|P9-2.jpg|P9-3.jpg",
      "DecContent1":  "Thermostat with Air Sensor and Equipment Module",
      "DecContent2":  "YTH6320R1001/U",
      "DecContent3":  "Control Your Home From Anywhere",
      "DecContent4":  "Keep your home energy-efficient with the FocusPRO 6000 Programmable Wireless Thermostat. Perfect for any connected home, the device features wireless internet connectivity, so you can monitor and control your heating and cooling systems whenever you\u0027re away from home.",
      "DecSelectAModel":  "Thermostat with Air Sensor and Equipment Module|Thermostat with Wireless Adapter|FocusPRO 6000 with RedLINK Gateway Outdoor Kit|5-1-1 Programmable Wireless Thermostat",
      "DecSpec1Image":  "",
      "DecSpec1Content1":  "",
      "DecSpec1Content2":  "",
      "DecSpec2Image":  "",
      "DecSpec2Content1":  "",
      "DecSpec2Content2":  "",
      "Page_URL":  "https://www.resideo.com/us/en/products/air/thermostats/programmable-thermostats/5-1-1-programmable-wireless-thermostat-th6320r1004-u/"
  },
  {
      "Id":  "10",
      "Category":  "THERMOSTAT",
      "Name":  "D6 Pro WiFi Ductless Controller",
      "Price":  "149.03",
      "Image":  "DC6000WF1001-c2-6.jpg",
      "DecImage1":  "HoneywellHome_Logo_Red_NP.png",
      "DecRollImages":  "P10-1.jpg|P10-2.jpg",
      "DecContent1":  "D6 Pro WiFi Ductless Controller",
      "DecContent2":  "DC6000WF1001/U",
      "DecContent3":  "Keep Your Ductless System Simple",
      "DecContent4":  "Forget complicated remote controls. Instead, use the D6 Pro WiFi Ductless Controller to quickly and intuitively choose a comfortable temperature. The controller acts like a thermostat, and it\u0027s easily installed with a wall mount or table stand.",
      "DecSelectAModel":  "D6 Pro WiFi Ductless Controller",
      "DecSpec1Image":  "P10-4.jpg",
      "DecSpec1Content1":  "PRODUCT OVERVIEW",
      "DecSpec1Content2":  "Your ductless heating and cooling system is simple and efficient, so choosing a comfortable temperature should be the same. Replace your complicated remote control with the D6 Pro WiFi Ductless Controller. The device works like a thermostat, so you can intuitively set your preferred temperature.                                                                                                               The pro ductless split controller works with more than 800 different models of ductless mini-split systems from the top manufacturers. Setup is completed right on the device with only six parameters, then easily install with the included wall mount or table stand.",
      "DecSpec2Image":  "P10-5.png",
      "DecSpec2Content1":  "Take It All With You",
      "DecSpec2Content2":  "D6 Pro WiFi Ductless Controller is supported by our Honeywell Home App, which lets you control your Honeywell Home devices from anywhere, in one connected platform.        The app\u0027s one-touch dashboard brings heating and cooling control, water leak detection and security all together with activity alerts, smart home integration, improved geofencing and improved usability.",
      "Page_URL":  "https://www.resideo.com/us/en/products/air/thermostats/programmable-thermostats/d6-pro-wifi-ductless-controller-dc6000wf1001-u/"
  },
  {
      "Id":  "11",
      "Category":  "THERMOSTAT",
      "Name":  "The Round Non-Programmable Thermostat",
      "Price":  "149.04",
      "Image":  "CT87N1001-c4-6.jpg",
      "DecImage1":  "HoneywellHome_Logo_Red_NP.png",
      "DecRollImages":  "P11-1.jpg|P11-2.jpg|P11-3.jpg",
      "DecContent1":  "The Round mercury free thermostat manual changeover single stage",
      "DecContent2":  "CT87N1001/U1",
      "DecContent3":  "Classic Design, Easy Use",
      "DecContent4":  "With its familiar circular design and simple twist action, The Round Non-Programmable Thermostat makes setting your ideal temperature quick and easy. Plus, the popular thermostat design fits perfectly into your home.",
      "DecSelectAModel":  "CT87K1004 The Round Heat Only Non-Prog Thermostat|The Round mercury free thermostat manual changeover single stage|CT87K1012/E1 Round Thermostat - White",
      "DecSpec1Image":  "P11-4.jpg",
      "DecSpec1Content1":  "PRODUCT OVERVIEW",
      "DecSpec1Content2":  "Embrace simplicity with The Round Non-Programmable Thermostat. The reliable, readable scale makes setting the exact temperature easy  including a model with large, raised markings and clicks at every 2-degree change so you can see and hear the change.                                                                                                                                                                                             Plus, the popular, familiar design fits effortlessly into your home decor. Let a professional install The Round Non-Programmable Thermostat today to receive a 5-year warranty. ",
      "DecSpec2Image":  "",
      "DecSpec2Content1":  "",
      "DecSpec2Content2":  "",
      "Page_URL":  "https://www.resideo.com/us/en/products/air/thermostats/non-programmable-thermostats/the-round-mercury-free-thermostat-manual-changeover-single-stage-ct87n1001-u1/"
  },
  {
      "Id":  "12",
      "Category":  "THERMOSTAT",
      "Name":  "WIFI SMART COLOR THERMOSTAT",
      "Price":  "169",
      "Image":  "RTH9585WF1004-c10-6.jpg",
      "DecImage1":  "HoneywellHome_Logo_Red_NP.png",
      "DecRollImages":  "P12-1.jpg|P12-2.jpg|P12-3.jpg",
      "DecContent1":  "WiFi Color Touchscreen Thermostat",
      "DecContent2":  "RTH9585WF1004/U",
      "DecContent3":  "Climate control tailored for you",
      "DecContent4":  "Completely customize your WiFi Smart Color Thermostat to match your lifestyle and decor. The ENERGY STAR certified smart thermostat lets you choose the temperature, schedule, display color and the devices you use to control it all.",
      "DecSelectAModel":  "WiFi Color Touchscreen Thermostat",
      "DecSpec1Image":  "P12-4.jpg",
      "DecSpec1Content1":  "PRODUCT OVERVIEW",
      "DecSpec1Content2":  "Customize your thermostat the way you personalize your home with the WiFi Smart Color Thermostat.                                                                                                                                                           The WiFi Smart Color Thermostat works seamlessly with Amazon Alexa and Google Home, as well as our mobile app, so you can control the temperature anywhere inside or outside your home. Smart response technology learns your schedule and temperature preferences to take the guesswork out of programming.                                                                        Plus, the full-color display is completely customizable to fit your unique style and match your home\u0027s decor. Enjoy versatility and performance with this smart home thermostat.                                                                                                                                                                                                                                                                                                                                                       Whether its a song belted in the shower or a whispered secret, your air goes beyond simply carrying oxygen to circulating memories. Heavy or light, hot or cold, always unique to your home, the air you feel is more than its temperature setting. Our Air products and services work with you and for you, supporting and creating more comfortable surroundings.",
      "DecSpec2Image":  "P12-5.png",
      "DecSpec2Content1":  "Take It All With You",
      "DecSpec2Content2":  "Gain further control over your home from anywhere, anytime when you access the WiFi Smart Color Thermostat through the Total Connect Comfort App.                                                    Monitor and adjust heating and cooling usage, stay on top of indoor humidity levels, even automatically receive email alerts related to safety, comfort and energy. The app is free, with no monthly monitoring fees and works with a wide range of popular connected devices.",
      "Page_URL":  "https://www.resideo.com/us/en/products/air/thermostats/wifi-thermostats/wifi-color-touchscreen-thermostat-rth9585wf1004-u/"
  }
]
